[project]
name = "tienda-inglesa"
version = "0.1.0"
description = "Assessment Tienda Inglesa"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastexcel>=0.20.2",
    "ipykernel>=7.3.0",
    "ipympl>=0.10.0",
    "matplotlib>=3.11.1",
    "mplcursors>=0.7.1",
    "numba>=0.66.0",
    "plotly>=6.9.0",
    "python-dateutil>=2.9.0",
    "polars>=1.43.0",
    "scipy>=1.18.0",
    "streamlit>=1.60.0",
    "tqdm>=4.70.0",
    "xlsxwriter>=3.2.9",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
